# default: &default
#   # adapter: sqlite3
#   adapter: postgresql
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.postgresql

# test:
#   <<: *default
#   database: db/test.postgresql

# production:
#   <<: *default
#   database: db/production.postgresql

development:
  adapter: postgresql
  encoding: unicode
  database: coffee-tycoon-backend
  pool: 5
  timeout: 5000

production:
  database: coffee-tycoon-backend
  adapter: postgresql
  

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  timeout: 5000