# default: &default
#   # adapter: sqlite3
#   adapter: postgresql
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.postgresql

# test:
#   <<: *default
#   database: db/test.postgresql

# production:
#   <<: *default
#   database: db/production.postgresql

development: &default
  adapter: postgresql
  encoding: unicode
  database: coffee-tycoon-backend
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

#this is what got the app to deploy on Heroku
production:
  <<: *default
  database: coffee-tycoon-backend
  #adapter: postgresql


test:
  <<: *default
  database: coffee-tycoon-backend


  #sample/scratch
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: <%= ENV['DATABASE_USERNAME'] %>
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   host: <%= ENV['DATABASE_HOST'] %>
#   port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>

# development:
#   <<: *default
#   database: coffee_tycoon_development

# test:
#   <<: *default
#   database: coffee_tycoon_test

# production:
#   <<: *default
#   database: coffee_tycoon_production
